<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="sales_leadExport1_sales_leadHttp_Service" targetNamespace="http://www.starstandard.org/STAR/5/Binding" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.starstandard.org/STAR/5" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:WL5G3N3="http://www.starstandard.org/STAR/5/Binding">
  <WL5G3N0:types>
    <xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.starstandard.org/STAR/5" xmlns="http://www.starstandard.org/STAR/5" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:star="http://www.starstandard.org/STAR/5" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="1.xsd"/>
      <xsd:include schemaLocation="1_20.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="AcknowledgeSalesLead">
    <WL5G3N0:part element="WL5G3N1:AcknowledgeSalesLead" name="AcknowledgeSalesLead"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="ProcessSalesLead">
    <WL5G3N0:part element="WL5G3N1:ProcessSalesLead" name="ProcessSalesLead"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="sales_lead">
    <WL5G3N0:operation name="processSalesLead">
      <WL5G3N0:input message="WL5G3N1:ProcessSalesLead"/>
      <WL5G3N0:output message="WL5G3N1:AcknowledgeSalesLead"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="sales_leadExport1_sales_leadHttpBinding" type="WL5G3N3:sales_lead">
    <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="processSalesLead">
      <WL5G3N2:operation soapAction="https://pleadoptimization.gm.com/process/sales_lead_bod"/>
      <WL5G3N0:input>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="sales_leadExport1_sales_leadHttpBindingQSService">
    <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
    <WL5G3N0:port binding="WL5G3N3:sales_leadExport1_sales_leadHttpBinding" name="sales_leadExport1_sales_leadHttpBindingQSPort">
      <WL5G3N2:address location="https://gsmc-osb-na-sit.gm.com:443/wssaml/CRM/SalesLead/1.0"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>