<wsdl:definitions targetNamespace="http://www.pfa.dk/alsb/soapfault/1/0/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fault="http://www.pfa.dk/alsb/soapfault/1/0/">
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="http://www.pfa.dk/alsb/soapfault/1/0/">
			<xsd:include schemaLocation="SoapFault.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="BusinessFault">
		<wsdl:part element="fault:businessFault" name="businessFault"/>
	</wsdl:message>
	<wsdl:message name="SevereFault">
		<wsdl:part element="fault:severeFault" name="severeFault"/>
	</wsdl:message>
	<wsdl:message name="ValidationFault">
		<wsdl:part element="fault:validationFault" name="validationFault"/>
	</wsdl:message>
	<wsdl:message name="TemporaryFault">
		<wsdl:part element="fault:temporaryFault" name="temporaryFault"/>
	</wsdl:message>
</wsdl:definitions>