//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.ApiManagement.WsdlProcessor.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.ApiManagement.WsdlProcessor.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding &apos;{0}&apos; not found..
        /// </summary>
        internal static string BindingNotFound {
            get {
                return ResourceManager.GetString("BindingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotResolveType {
            get {
                return ResourceManager.GetString("CannotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve import from &apos;{0}&apos;. The request failed with error &apos;{1}&apos; and message &apos;{2}&apos;..
        /// </summary>
        internal static string FailedToImport {
            get {
                return ResourceManager.GetString("FailedToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve import from &apos;{0}&apos;. The request response code was &apos;{1}&apos; and parsing the response content failed with &apos;{2}&apos; and message &apos;{3}&apos;..
        /// </summary>
        internal static string FailedToParseImportedSchemaResponse {
            get {
                return ResourceManager.GetString("FailedToParseImportedSchemaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve referenced input message &apos;{0}&apos;..
        /// </summary>
        internal static string InputMessageNotFound {
            get {
                return ResourceManager.GetString("InputMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface &apos;{0}&apos; not found..
        /// </summary>
        internal static string InterfaceNotFound {
            get {
                return ResourceManager.GetString("InterfaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided schema &apos;{0}&apos; is invalid and cannot be parsed..
        /// </summary>
        internal static string InvalidXmlSchema {
            get {
                return ResourceManager.GetString("InvalidXmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded &apos;{0}&apos; bindings..
        /// </summary>
        internal static string LoadedBindings {
            get {
                return ResourceManager.GetString("LoadedBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded &apos;{0}&apos; interfaces..
        /// </summary>
        internal static string LoadedInterfaces {
            get {
                return ResourceManager.GetString("LoadedInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded &apos;{0}&apos; messages..
        /// </summary>
        internal static string LoadedMessages {
            get {
                return ResourceManager.GetString("LoadedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schemas found..
        /// </summary>
        internal static string LoadedNoSchemas {
            get {
                return ResourceManager.GetString("LoadedNoSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Namespace: &apos;{0}&apos;..
        /// </summary>
        internal static string LoadedSchema {
            get {
                return ResourceManager.GetString("LoadedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded &apos;{0}&apos; schemas..
        /// </summary>
        internal static string LoadedSchemas {
            get {
                return ResourceManager.GetString("LoadedSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded &apos;{0}&apos; services..
        /// </summary>
        internal static string LoadedServices {
            get {
                return ResourceManager.GetString("LoadedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded &apos;{0}&apos; types..
        /// </summary>
        internal static string LoadedTypes {
            get {
                return ResourceManager.GetString("LoadedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interfaces found..
        /// </summary>
        internal static string NoInterfacesFound {
            get {
                return ResourceManager.GetString("NoInterfacesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Operation &apos;{0}&apos; is not supported. Only Request-response and Solicit-response Operations are supported..
        /// </summary>
        internal static string NotificationOperationNotSupported {
            get {
                return ResourceManager.GetString("NotificationOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-way Operation &apos;{0}&apos; is not supported. Only Request-response and Solicit-response Operations are supported..
        /// </summary>
        internal static string OneWayOperationNotSupported {
            get {
                return ResourceManager.GetString("OneWayOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate unique resource identifiers for operations, both operation names and SOAP actions conflict. Please modify the WSDL document to avoid redundant operation names, including redundant use of empty string..
        /// </summary>
        internal static string OperationsActionsBothDoConflict {
            get {
                return ResourceManager.GetString("OperationsActionsBothDoConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve referenced output message &apos;{0}&apos;..
        /// </summary>
        internal static string OutputMessageNotFound {
            get {
                return ResourceManager.GetString("OutputMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed parsing XML..
        /// </summary>
        internal static string ParsingXmlComplete {
            get {
                return ResourceManager.GetString("ParsingXmlComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started parsing XML..
        /// </summary>
        internal static string ParsingXmlStarted {
            get {
                return ResourceManager.GetString("ParsingXmlStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element named &apos;{0}&apos; has a recursive definition. Recursive types are not supported..
        /// </summary>
        internal static string RecursiveTypesNotSupported {
            get {
                return ResourceManager.GetString("RecursiveTypesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soap:address element with location attribute is required in the wsdl:port element named &apos;{0}&apos; of the WSDL document..
        /// </summary>
        internal static string SoapAddressLocationRequired {
            get {
                return ResourceManager.GetString("SoapAddressLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import API from WSDL..
        /// </summary>
        internal static string UnableToImportApiFromWsdl {
            get {
                return ResourceManager.GetString("UnableToImportApiFromWsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse WSDL..
        /// </summary>
        internal static string UnableToParseWsdl {
            get {
                return ResourceManager.GetString("UnableToParseWsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected null binding operation or null operation. Please check the WSDL document operations and bindings..
        /// </summary>
        internal static string UnexpectedNullOperationOrBinding {
            get {
                return ResourceManager.GetString("UnexpectedNullOperationOrBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown WSDL Version: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownWsdlVersion {
            get {
                return ResourceManager.GetString("UnknownWsdlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSDL 2.0 currently not supported for import..
        /// </summary>
        internal static string Wsdl20CurrentlyNotSupported {
            get {
                return ResourceManager.GetString("Wsdl20CurrentlyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WsdlVersion: &apos;{0}&apos; TargetNamespace: &apos;{1}&apos;..
        /// </summary>
        internal static string WsdlIdentification {
            get {
                return ResourceManager.GetString("WsdlIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSD Schema http://www.w3.org/2000/10/XMLSchema is not supported. Use http://www.w3.org/2001/XMLSchema instead..
        /// </summary>
        internal static string WsdlImportRuleCheckXmlSchemaNamespace {
            get {
                return ResourceManager.GetString("WsdlImportRuleCheckXmlSchemaNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSDL Import is currently not supported..
        /// </summary>
        internal static string WsdlImportRuleImportNotSupported {
            get {
                return ResourceManager.GetString("WsdlImportRuleImportNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message &apos;{0}&apos; contains multiple parts..
        /// </summary>
        internal static string WsdlImportRuleSingleParts {
            get {
                return ResourceManager.GetString("WsdlImportRuleSingleParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSDL message &apos;{0}&apos; has no name attribute. The name attribute is required per WSDL 1.1 specification..
        /// </summary>
        internal static string WsdlMessageNameAttributeNotFound {
            get {
                return ResourceManager.GetString("WsdlMessageNameAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed WSDL verification. WSDL is considered valid..
        /// </summary>
        internal static string WsdlPrecheckComplete {
            get {
                return ResourceManager.GetString("WsdlPrecheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed WSDL verification..
        /// </summary>
        internal static string WsdlPrecheckFailed {
            get {
                return ResourceManager.GetString("WsdlPrecheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: &apos;{0}&apos; TargetNamespace: &apos;{1}&apos;..
        /// </summary>
        internal static string XsdImport {
            get {
                return ResourceManager.GetString("XsdImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location &apos;{0}&apos; cannot be resolved. Cannot resolve WSDL Imports that use relative URLs..
        /// </summary>
        internal static string XsdImportFailure {
            get {
                return ResourceManager.GetString("XsdImportFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos; imports..
        /// </summary>
        internal static string XsdImportsFound {
            get {
                return ResourceManager.GetString("XsdImportsFound", resourceCulture);
            }
        }
    }
}
